server:
  port: 8195
  servlet:
    context-path: /market-payment
integrations:
  core-service:
    url: http://localhost:5555/core

common:
  brand-name: Scooter-Market

common:
  brand-name: Scooter-Market


## PayPal config
## to obtain client id and secret id visit https://developer.paypal.com/home/
## register test account and use business-account credentials here and personal account for payment
paypal:
  clientId: ##your client-id
  clientSecret: ##your client-secret
  currency: RUB

