server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  cart-service:
    url: http://localhost:8191/market-cart
jwt:
  secret: sdgfklj289fkldsnj8347thkyoi@go7890@;ljkkld;lsgkj;l834#bfxkblmj
  lifetime: 36000000
paypal:
  client-id: AV1c839UqJ4yKO_1sFCgy2psJ8ugyjjwa764lwC3wqCnL6QJSOfTuwa83YJg_6Z8QMtJ4CZY3AngbJlT
  client-secret: EIJUBWniPWhDVml6hSS4KBq5EXs2uoeAt7wztkXum_CfqDVKjtLp_pzv34R9kZnuzORUE1HJs1_LRTu1